ops:
  master:
    hostname: "localhost"
    port_grpc: 14010
  worker:
    localDir: "/Users/admin/Documents/OPS/"
    port_grpc: 14020
    port_hadoop_grpc: 14030

etcd:
  endpoints:
    - hostname: "http://202.120.40.4"
      port: 12379
